function createImageSet(key, name, shots) {
    return shots.map((shot, index) => ({
        imageid: `seed-${key}-${index + 1}`,
        imagename: `${name} ${shot.label || index + 1}`,
        url: shot.url,
        sourceUrl: shot.sourceUrl || shot.url,
    }));
}
const types = ["woman", "man", "girl", "boy", "baby"];
const categories = ["tops", "hoodies", "dresses", "outerwear", "accessories"];
const colours = [
    { colourname: "black", hex: "111827" },
    { colourname: "white", hex: "F8FAFC" },
    { colourname: "navy", hex: "1D3557" },
    { colourname: "sand", hex: "D8C3A5" },
    { colourname: "rose", hex: "E58CA8" },
    { colourname: "sage", hex: "8AA38B" },
    { colourname: "sky", hex: "8EC9F1" },
    { colourname: "cocoa", hex: "7A5A46" },
    { colourname: "butter", hex: "F2D98D" },
];
const sizes = ["XS", "S", "M", "L", "XL"];
const shippers = [
    { name: "Ninja Van", phone: "+65 3158 1111" },
    { name: "J&T Express", phone: "+65 6931 6666" },
    { name: "SingPost", phone: "+65 1605" },
];
const users = [
    {
        key: "admin",
        name: "DailyHype Admin",
        emailFrom: "adminEmail",
        passwordFrom: "adminPassword",
        phone: "90000001",
        gender: "M",
        role: "admin",
        status: "active",
        method: "normal",
        verified_email: true,
        addresses: [],
    },
    {
        key: "manager",
        name: "Ops Manager",
        email: "ops@dailyhype.local",
        password: "ChangeMe123!",
        phone: "90000008",
        gender: "M",
        role: "manager",
        status: "active",
        method: "normal",
        verified_email: true,
        addresses: [],
    },
    {
        key: "customerPrimary",
        name: "Mia Tan",
        emailFrom: "customerEmail",
        passwordFrom: "customerPassword",
        phone: "90000002",
        gender: "F",
        role: "customer",
        status: "active",
        method: "normal",
        verified_email: true,
        addresses: [
            {
                fullname: "Mia Tan",
                phone: "90000002",
                postal_code: "238801",
                block_no: "100",
                street: "Orchard Road",
                building: "DailyHype Residence",
                unit_no: "#08-08",
                region: "Central",
                is_default: true,
            },
            {
                fullname: "Mia Tan",
                phone: "90000002",
                postal_code: "408564",
                block_no: "18",
                street: "East Coast Road",
                building: "Seabreeze Apartments",
                unit_no: "#11-03",
                region: "East",
                is_default: false,
            },
        ],
    },
    {
        key: "customerSecondary",
        name: "Ryan Lim",
        email: "ryan.lim@dailyhype.local",
        password: "ChangeMe123!",
        phone: "90000003",
        gender: "M",
        role: "customer",
        status: "active",
        method: "normal",
        verified_email: true,
        addresses: [
            {
                fullname: "Ryan Lim",
                phone: "90000003",
                postal_code: "569880",
                block_no: "52",
                street: "Upper Thomson Road",
                building: "Thomson Heights",
                unit_no: "#06-11",
                region: "North",
                is_default: true,
            },
        ],
    },
    {
        key: "customerThird",
        name: "Sara Ng",
        email: "sara.ng@dailyhype.local",
        password: "ChangeMe123!",
        phone: "90000004",
        gender: "F",
        role: "customer",
        status: "active",
        method: "normal",
        verified_email: true,
        addresses: [
            {
                fullname: "Sara Ng",
                phone: "90000004",
                postal_code: "098585",
                block_no: "3",
                street: "Telok Blangah Rise",
                building: "Harbour View",
                unit_no: "#09-14",
                region: "South",
                is_default: true,
            },
        ],
    },
];
const products = [
    {
        key: "harbor-knit-polo",
        name: "Blue & Black Check Shirt",
        description: "Cotton check shirt with a clean casual fit and sharp contrast pattern for everyday wear.",
        unitPrice: 29.99,
        type: "man",
        category: "tops",
        rating: 4.6,
        soldqty: 84,
        createdAtDaysAgo: 28,
        images: createImageSet("harbor-knit-polo", "Blue & Black Check Shirt", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp" },
        ]),
        details: [
            { colour: "navy", size: "M", qty: 14 },
            { colour: "navy", size: "L", qty: 12 },
            { colour: "black", size: "M", qty: 9 },
            { colour: "white", size: "L", qty: 7 },
        ],
    },
    {
        key: "essential-heavy-tee",
        name: "Gigabyte Aorus Men Tshirt",
        description: "Graphic cotton tee with a bold front print and a regular fit that works well on weekends.",
        unitPrice: 24.99,
        type: "man",
        category: "tops",
        rating: 4.5,
        soldqty: 73,
        createdAtDaysAgo: 25,
        images: createImageSet("essential-heavy-tee", "Gigabyte Aorus Men Tshirt", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp" },
        ]),
        details: [
            { colour: "black", size: "M", qty: 13 },
            { colour: "black", size: "L", qty: 10 },
            { colour: "white", size: "M", qty: 8 },
            { colour: "navy", size: "L", qty: 6 },
        ],
    },
    {
        key: "varsity-zip-hoodie",
        name: "Urban Fleece Hoodie",
        description: "Soft pullover hoodie with an easy streetwear look for cooler evenings and everyday layering.",
        unitPrice: 49.9,
        type: "man",
        category: "hoodies",
        rating: 4.7,
        soldqty: 39,
        createdAtDaysAgo: 4,
        images: createImageSet("varsity-zip-hoodie", "Urban Fleece Hoodie", [
            {
                label: "lookbook",
                url: "https://images.unsplash.com/photo-1519689373023-dd07c7988603?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=talen-de-st-croix-EXr_Qif3Vl8-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/EXr_Qif3Vl8/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "navy", size: "M", qty: 9 },
            { colour: "navy", size: "L", qty: 8 },
            { colour: "sand", size: "M", qty: 6 },
            { colour: "black", size: "L", qty: 5 },
        ],
    },
    {
        key: "transit-overshirt-jacket",
        name: "Men Check Shirt",
        description: "Overshirt-inspired check piece that wears well open over a tee or buttoned as a standalone shirt.",
        unitPrice: 27.99,
        type: "man",
        category: "outerwear",
        rating: 4.4,
        soldqty: 58,
        createdAtDaysAgo: 18,
        images: createImageSet("transit-overshirt-jacket", "Men Check Shirt", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp" },
        ]),
        details: [
            { colour: "black", size: "M", qty: 10 },
            { colour: "white", size: "L", qty: 9 },
            { colour: "sand", size: "M", qty: 7 },
            { colour: "navy", size: "L", qty: 6 },
        ],
    },
    {
        key: "studio-rib-tank",
        name: "Corset With Black Skirt",
        description: "Statement black corset-and-skirt pairing with a sleek dressy finish for evening styling.",
        unitPrice: 79.99,
        type: "woman",
        category: "tops",
        rating: 4.5,
        soldqty: 41,
        createdAtDaysAgo: 16,
        images: createImageSet("studio-rib-tank", "Corset With Black Skirt", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/2.webp" },
        ]),
        details: [
            { colour: "black", size: "S", qty: 8 },
            { colour: "black", size: "M", qty: 9 },
            { colour: "white", size: "M", qty: 5 },
            { colour: "rose", size: "S", qty: 4 },
        ],
    },
    {
        key: "linen-slip-dress",
        name: "Black Women's Gown",
        description: "Long black gown with elegant movement and a polished silhouette for formal occasions.",
        unitPrice: 129.99,
        type: "woman",
        category: "dresses",
        rating: 4.8,
        soldqty: 26,
        createdAtDaysAgo: 7,
        images: createImageSet("linen-slip-dress", "Black Women's Gown", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/2.webp" },
        ]),
        details: [
            { colour: "black", size: "S", qty: 7 },
            { colour: "black", size: "M", qty: 9 },
            { colour: "cocoa", size: "L", qty: 4 },
            { colour: "white", size: "M", qty: 3 },
        ],
    },
    {
        key: "city-windbreaker",
        name: "Marni Red & Black Suit",
        description: "Tailored red-and-black set with a sharper finish for dressed-up events and statement styling.",
        unitPrice: 179.99,
        type: "woman",
        category: "outerwear",
        rating: 4.6,
        soldqty: 18,
        createdAtDaysAgo: 3,
        images: createImageSet("city-windbreaker", "Marni Red & Black Suit", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp" },
        ]),
        details: [
            { colour: "black", size: "M", qty: 6 },
            { colour: "rose", size: "S", qty: 5 },
            { colour: "cocoa", size: "M", qty: 4 },
            { colour: "white", size: "L", qty: 3 },
        ],
    },
    {
        key: "downtown-crossbody-bag",
        name: "Blue Women's Handbag",
        description: "Structured handbag with an everyday size, polished finish, and a look that works from office to dinner.",
        unitPrice: 49.99,
        type: "woman",
        category: "accessories",
        rating: 4.4,
        soldqty: 67,
        createdAtDaysAgo: 2,
        images: createImageSet("downtown-crossbody-bag", "Blue Women's Handbag", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/2.webp" },
        ]),
        details: [
            { colour: "navy", size: "M", qty: 12 },
            { colour: "sky", size: "M", qty: 10 },
            { colour: "black", size: "M", qty: 8 },
        ],
    },
    {
        key: "bloom-party-dress",
        name: "Girl Summer Dress",
        description: "Light summer dress with an easy playful cut for holidays, birthdays, and warm weekend outings.",
        unitPrice: 19.99,
        type: "girl",
        category: "dresses",
        rating: 4.7,
        soldqty: 55,
        createdAtDaysAgo: 14,
        images: createImageSet("bloom-party-dress", "Girl Summer Dress", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp" },
        ]),
        details: [
            { colour: "rose", size: "XS", qty: 8 },
            { colour: "sky", size: "S", qty: 7 },
            { colour: "white", size: "S", qty: 6 },
        ],
    },
    {
        key: "sunshine-cardigan-set",
        name: "Blue Frock",
        description: "Bright frock with a youthful shape and party-ready finish that still feels easy to wear.",
        unitPrice: 29.99,
        type: "girl",
        category: "dresses",
        rating: 4.5,
        soldqty: 43,
        createdAtDaysAgo: 20,
        images: createImageSet("sunshine-cardigan-set", "Blue Frock", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp" },
        ]),
        details: [
            { colour: "sky", size: "XS", qty: 7 },
            { colour: "sky", size: "S", qty: 6 },
            { colour: "white", size: "S", qty: 5 },
        ],
    },
    {
        key: "weekend-skirt-set",
        name: "Tartan Dress",
        description: "Classic tartan dress with a neat structured look for family gatherings and smarter casual days.",
        unitPrice: 39.99,
        type: "girl",
        category: "dresses",
        rating: 4.6,
        soldqty: 34,
        createdAtDaysAgo: 10,
        images: createImageSet("weekend-skirt-set", "Tartan Dress", [
            { label: "front", url: "https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp" },
            { label: "detail", url: "https://cdn.dummyjson.com/product-images/tops/tartan-dress/2.webp" },
        ]),
        details: [
            { colour: "rose", size: "XS", qty: 6 },
            { colour: "navy", size: "S", qty: 5 },
            { colour: "black", size: "S", qty: 5 },
        ],
    },
    {
        key: "crew-stripe-tee",
        name: "Scout Cotton Tee",
        description: "Soft crew-neck tee with an easy casual look built for school days and relaxed weekends.",
        unitPrice: 21.9,
        type: "boy",
        category: "tops",
        rating: 4.4,
        soldqty: 49,
        createdAtDaysAgo: 22,
        images: createImageSet("crew-stripe-tee", "Scout Cotton Tee", [
            {
                label: "lookbook",
                url: "https://images.unsplash.com/photo-1626976666226-97ae60d89636?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=zachary-kadolph-mOZINGvk6ro-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/mOZINGvk6ro/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "navy", size: "S", qty: 9 },
            { colour: "white", size: "M", qty: 8 },
            { colour: "black", size: "M", qty: 6 },
        ],
    },
    {
        key: "mini-explorer-hoodie",
        name: "Trail Hoodie",
        description: "Comfort-first hoodie for cooler weather with a young everyday fit and soft fleece feel.",
        unitPrice: 34.9,
        type: "boy",
        category: "hoodies",
        rating: 4.6,
        soldqty: 37,
        createdAtDaysAgo: 5,
        images: createImageSet("mini-explorer-hoodie", "Trail Hoodie", [
            {
                label: "lookbook",
                url: "https://images.unsplash.com/photo-1774188264019-7e7f13cb36be?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=preillumination-seth-i1MyGHK18R8-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/i1MyGHK18R8/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "butter", size: "S", qty: 7 },
            { colour: "navy", size: "M", qty: 8 },
            { colour: "black", size: "M", qty: 5 },
        ],
    },
    {
        key: "playground-jogger-set",
        name: "Everyday Layer Tee",
        description: "Easy layer tee with a casual modern look that pairs well with joggers, shorts, and denim.",
        unitPrice: 23.9,
        type: "boy",
        category: "tops",
        rating: 4.3,
        soldqty: 31,
        createdAtDaysAgo: 12,
        images: createImageSet("playground-jogger-set", "Everyday Layer Tee", [
            {
                label: "lookbook",
                url: "https://images.unsplash.com/photo-1606524367384-a21dc1c95894?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=laura-alvarez-Ugve_40vhDU-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/Ugve_40vhDU/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "sage", size: "S", qty: 8 },
            { colour: "sky", size: "M", qty: 7 },
            { colour: "navy", size: "M", qty: 6 },
        ],
    },
    {
        key: "tiny-day-romper",
        name: "Cozy Plaid Baby Set",
        description: "Soft plaid baby set styling with a comfortable easy fit for photos, visits, and cooler days.",
        unitPrice: 18.9,
        type: "baby",
        category: "tops",
        rating: 4.9,
        soldqty: 64,
        createdAtDaysAgo: 15,
        images: createImageSet("tiny-day-romper", "Cozy Plaid Baby Set", [
            {
                label: "lookbook",
                url: "https://images.unsplash.com/flagged/photo-1580012650365-75d4fa5bd5c1?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=evelyn-semenyuk-eG_E38a10oM-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/eG_E38a10oM/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "sand", size: "XS", qty: 10 },
            { colour: "sand", size: "S", qty: 9 },
            { colour: "white", size: "XS", qty: 8 },
        ],
    },
    {
        key: "cloud-knit-sleepsuit",
        name: "Nursery Gift Set",
        description: "Soft babywear gift set presentation with warm neutral tones and a cozy newborn feel.",
        unitPrice: 29.9,
        type: "baby",
        category: "outerwear",
        rating: 4.8,
        soldqty: 26,
        createdAtDaysAgo: 9,
        images: createImageSet("cloud-knit-sleepsuit", "Nursery Gift Set", [
            {
                label: "basket",
                url: "https://images.unsplash.com/photo-1768693602418-260d828b878d?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=carmela-lustre-AkPas1rErdE-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/AkPas1rErdE/download?force=true&w=1200",
            },
            {
                label: "closet",
                url: "https://images.unsplash.com/photo-1760856269352-d0d5ca6ad3c7?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=nat-39-eX2QWaq4-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/39-eX2QWaq4/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "sky", size: "XS", qty: 9 },
            { colour: "sky", size: "S", qty: 8 },
            { colour: "white", size: "S", qty: 6 },
        ],
    },
    {
        key: "little-bear-cap",
        name: "Little Bear Knit Cap",
        description: "Cozy knit cap look for newborn styling with a soft snug fit and classic babywear feel.",
        unitPrice: 16.9,
        type: "baby",
        category: "accessories",
        rating: 4.6,
        soldqty: 29,
        createdAtDaysAgo: 11,
        images: createImageSet("little-bear-cap", "Little Bear Knit Cap", [
            {
                label: "portrait",
                url: "https://images.unsplash.com/photo-1545877872-3e6582cbc37c?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=minnie-zhou-6ODIvvWtR-4-unsplash.jpg&w=1200",
                sourceUrl: "https://unsplash.com/photos/6ODIvvWtR-4/download?force=true&w=1200",
            },
        ]),
        details: [
            { colour: "cocoa", size: "XS", qty: 8 },
            { colour: "butter", size: "XS", qty: 7 },
            { colour: "sand", size: "S", qty: 6 },
        ],
    },
];
const carts = [
    {
        customerKey: "customerPrimary",
        items: [
            { productKey: "city-windbreaker", detailIndex: 1, qty: 1 },
            { productKey: "bloom-party-dress", detailIndex: 0, qty: 1 },
        ],
    },
    {
        customerKey: "customerSecondary",
        items: [
            { productKey: "transit-overshirt-jacket", detailIndex: 0, qty: 1 },
            { productKey: "playground-jogger-set", detailIndex: 2, qty: 1 },
            { productKey: "little-bear-cap", detailIndex: 1, qty: 2 },
        ],
    },
    {
        customerKey: "customerThird",
        items: [
            { productKey: "downtown-crossbody-bag", detailIndex: 0, qty: 1 },
        ],
    },
];
const orders = [
    {
        orderid: 202604150001,
        paymentid: 202604150101,
        refundid: 202604150201,
        customerKey: "customerPrimary",
        addressIndex: 0,
        createdAtDaysAgo: 9,
        shippingfee: 4.9,
        gst: 9,
        orderstatus: "received",
        delivery: {
            trackingnumber: "DH-TRACK-2001",
            shipper: "Ninja Van",
            daysAgo: 6,
            deliverystatus: "completed",
            deliverystatusdetail: "Delivered to customer",
        },
        items: [
            { productKey: "harbor-knit-polo", detailIndex: 0, qty: 1 },
            { productKey: "linen-slip-dress", detailIndex: 1, qty: 1 },
        ],
        reviews: [
            { productKey: "harbor-knit-polo", detailIndex: 0, rating: 5, text: "Premium feel, clean fit, and the colour looks even better in person." },
            { productKey: "linen-slip-dress", detailIndex: 1, rating: 4, text: "The fabric is breezy and flattering. Great for warm weekends." },
        ],
        refund: {
            productKey: "harbor-knit-polo",
            detailIndex: 0,
            amount: 42.9,
            qty: 1,
            category: "size issue",
            reason: "Sample refund request for testing the returns flow.",
            status: "pending",
        },
    },
    {
        orderid: 202604150002,
        paymentid: 202604150102,
        customerKey: "customerPrimary",
        addressIndex: 1,
        createdAtDaysAgo: 4,
        shippingfee: 4.9,
        gst: 9,
        orderstatus: "delivered",
        delivery: {
            trackingnumber: "DH-TRACK-2002",
            shipper: "J&T Express",
            daysAgo: 1,
            deliverystatus: "out for delivery",
            deliverystatusdetail: "Courier is arriving today",
        },
        items: [
            { productKey: "city-windbreaker", detailIndex: 0, qty: 1 },
            { productKey: "downtown-crossbody-bag", detailIndex: 1, qty: 1 },
        ],
        chatMessage: "Your parcel is out with the driver and should arrive before 9pm.",
    },
    {
        orderid: 202604150003,
        paymentid: 202604150103,
        customerKey: "customerPrimary",
        addressIndex: 0,
        createdAtDaysAgo: 1,
        shippingfee: 4.9,
        gst: 9,
        orderstatus: "in progress",
        delivery: {
            trackingnumber: "DH-TRACK-2003",
            shipper: "SingPost",
            daysAgo: 0,
            deliverystatus: "processing",
            deliverystatusdetail: "Warehouse team is packing the order",
        },
        items: [
            { productKey: "weekend-skirt-set", detailIndex: 0, qty: 1 },
            { productKey: "little-bear-cap", detailIndex: 0, qty: 1 },
        ],
        chatMessage: "We have packed your order and will hand it over to the courier shortly.",
    },
    {
        orderid: 202604150004,
        paymentid: 202604150104,
        customerKey: "customerSecondary",
        addressIndex: 0,
        createdAtDaysAgo: 3,
        shippingfee: 4.9,
        gst: 9,
        orderstatus: "confirmed",
        delivery: {
            trackingnumber: "DH-TRACK-2004",
            shipper: "Ninja Van",
            daysAgo: 2,
            deliverystatus: "confirmed",
            deliverystatusdetail: "Delivery slot confirmed and awaiting pickup",
        },
        items: [
            { productKey: "varsity-zip-hoodie", detailIndex: 1, qty: 1 },
            { productKey: "crew-stripe-tee", detailIndex: 0, qty: 2 },
        ],
    },
    {
        orderid: 202604150005,
        paymentid: 202604150105,
        customerKey: "customerThird",
        addressIndex: 0,
        createdAtDaysAgo: 11,
        shippingfee: 4.9,
        gst: 9,
        orderstatus: "received",
        delivery: {
            trackingnumber: "DH-TRACK-2005",
            shipper: "J&T Express",
            daysAgo: 8,
            deliverystatus: "completed",
            deliverystatusdetail: "Delivered and received",
        },
        items: [
            { productKey: "tiny-day-romper", detailIndex: 0, qty: 1 },
            { productKey: "cloud-knit-sleepsuit", detailIndex: 1, qty: 1 },
        ],
        reviews: [
            { productKey: "tiny-day-romper", detailIndex: 0, rating: 5, text: "Super soft fabric and really practical snaps for quick changes." },
        ],
    },
];
module.exports = {
    types,
    categories,
    colours,
    sizes,
    shippers,
    users,
    products,
    carts,
    orders,
};
