CREATE TABLE IF NOT EXISTS role (
  roleid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rolename TEXT NOT NULL UNIQUE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS type (
  typeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  typename TEXT NOT NULL UNIQUE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS category (
  categoryid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoryname TEXT NOT NULL UNIQUE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS colour (
  colourid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  colourname TEXT NOT NULL UNIQUE,
  name TEXT GENERATED ALWAYS AS (colourname) STORED,
  hex TEXT NOT NULL,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS size (
  sizeid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sizename TEXT NOT NULL UNIQUE,
  name TEXT GENERATED ALWAYS AS (sizename) STORED,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS image (
  imageid TEXT PRIMARY KEY,
  imagename TEXT NOT NULL,
  url TEXT NOT NULL,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product (
  productid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  productname TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  unitprice NUMERIC(10, 2) NOT NULL DEFAULT 0,
  categoryid INTEGER NOT NULL REFERENCES category(categoryid) ON DELETE RESTRICT,
  typeid INTEGER NOT NULL REFERENCES type(typeid) ON DELETE RESTRICT,
  rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
  soldqty INTEGER NOT NULL DEFAULT 0,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS productdetail (
  productdetailid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  productid INTEGER NOT NULL REFERENCES product(productid) ON DELETE CASCADE,
  colourid INTEGER NOT NULL REFERENCES colour(colourid) ON DELETE RESTRICT,
  sizeid INTEGER NOT NULL REFERENCES size(sizeid) ON DELETE RESTRICT,
  qty INTEGER NOT NULL DEFAULT 0,
  productstatus TEXT NOT NULL DEFAULT 'in stock',
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (productid, colourid, sizeid)
);

CREATE TABLE IF NOT EXISTS productimage (
  productid INTEGER NOT NULL REFERENCES product(productid) ON DELETE CASCADE,
  imageid TEXT NOT NULL REFERENCES image(imageid) ON DELETE CASCADE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (productid, imageid)
);

CREATE TABLE IF NOT EXISTS appuser (
  userid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT,
  phone TEXT,
  gender TEXT,
  roleid INTEGER NOT NULL REFERENCES role(roleid) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'active',
  method TEXT NOT NULL DEFAULT 'normal',
  imageid TEXT REFERENCES image(imageid) ON DELETE SET NULL,
  verified_email BOOLEAN NOT NULL DEFAULT FALSE,
  code TEXT,
  createdcodeat TIMESTAMPTZ,
  refreshtoken TEXT,
  address TEXT,
  region TEXT
);

CREATE TABLE IF NOT EXISTS address (
  address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname TEXT NOT NULL,
  phone TEXT NOT NULL,
  postal_code TEXT NOT NULL,
  block_no TEXT NOT NULL,
  street TEXT,
  building TEXT,
  unit_no TEXT,
  region TEXT,
  userid BIGINT NOT NULL REFERENCES appuser(userid) ON DELETE CASCADE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cart (
  cartid BIGINT PRIMARY KEY,
  productdetailid INTEGER NOT NULL REFERENCES productdetail(productdetailid) ON DELETE CASCADE,
  qty INTEGER NOT NULL DEFAULT 1,
  userid BIGINT NOT NULL REFERENCES appuser(userid) ON DELETE CASCADE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (userid, productdetailid)
);

CREATE TABLE IF NOT EXISTS deliveryshipper (
  shipperid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  phone TEXT,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS delivery (
  deliveryid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deliverydate TIMESTAMPTZ NOT NULL,
  deliverystatus TEXT NOT NULL,
  deliverystatusdetail TEXT NOT NULL,
  trackingnumber TEXT NOT NULL UNIQUE,
  shipperid INTEGER REFERENCES deliveryshipper(shipperid) ON DELETE SET NULL,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedatconfirmed TIMESTAMPTZ,
  updatedatcheck TIMESTAMPTZ,
  updatedatway TIMESTAMPTZ,
  updatedatpick TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS productorder (
  orderid BIGINT PRIMARY KEY,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  totalqty INTEGER NOT NULL DEFAULT 0,
  totalamount NUMERIC(10, 2) NOT NULL DEFAULT 0,
  deliveryaddress TEXT NOT NULL,
  orderstatus TEXT NOT NULL DEFAULT 'in progress',
  userid BIGINT NOT NULL REFERENCES appuser(userid) ON DELETE CASCADE,
  shippingfee NUMERIC(10, 2) NOT NULL DEFAULT 0,
  gst NUMERIC(5, 2) NOT NULL DEFAULT 0,
  deliveryid INTEGER REFERENCES delivery(deliveryid) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS productorderitem (
  productdetailid INTEGER NOT NULL REFERENCES productdetail(productdetailid) ON DELETE RESTRICT,
  orderid BIGINT NOT NULL REFERENCES productorder(orderid) ON DELETE CASCADE,
  qty INTEGER NOT NULL DEFAULT 1,
  unitprice NUMERIC(10, 2) NOT NULL DEFAULT 0,
  deliveryid INTEGER REFERENCES delivery(deliveryid) ON DELETE SET NULL,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (orderid, productdetailid)
);

CREATE TABLE IF NOT EXISTS payment (
  paymentid BIGINT PRIMARY KEY,
  orderid BIGINT NOT NULL UNIQUE REFERENCES productorder(orderid) ON DELETE CASCADE,
  paymentmethod TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  paymentstatus TEXT NOT NULL,
  transactionid TEXT,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS review (
  reviewid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating INTEGER NOT NULL,
  reviewdescription TEXT NOT NULL DEFAULT '',
  userid BIGINT NOT NULL REFERENCES appuser(userid) ON DELETE CASCADE,
  productid INTEGER NOT NULL REFERENCES product(productid) ON DELETE CASCADE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  productdetailid INTEGER REFERENCES productdetail(productdetailid) ON DELETE SET NULL,
  orderid BIGINT REFERENCES productorder(orderid) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reviewimage (
  reviewid INTEGER NOT NULL REFERENCES review(reviewid) ON DELETE CASCADE,
  imageid TEXT NOT NULL REFERENCES image(imageid) ON DELETE CASCADE,
  PRIMARY KEY (reviewid, imageid)
);

CREATE TABLE IF NOT EXISTS orderrefund (
  refundid BIGINT PRIMARY KEY,
  refundamount NUMERIC(10, 2) NOT NULL,
  refundreason TEXT,
  refundcategory TEXT,
  refundstatus TEXT NOT NULL DEFAULT 'pending',
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  orderid BIGINT NOT NULL REFERENCES productorder(orderid) ON DELETE CASCADE,
  productdetailid INTEGER NOT NULL REFERENCES productdetail(productdetailid) ON DELETE CASCADE,
  refundqty INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS refundimage (
  refundid BIGINT NOT NULL REFERENCES orderrefund(refundid) ON DELETE CASCADE,
  imageid TEXT NOT NULL REFERENCES image(imageid) ON DELETE CASCADE,
  PRIMARY KEY (refundid, imageid)
);

CREATE TABLE IF NOT EXISTS chat (
  roomid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adminuserid BIGINT REFERENCES appuser(userid) ON DELETE SET NULL,
  deliveryid INTEGER REFERENCES delivery(deliveryid) ON DELETE CASCADE,
  useruserid BIGINT REFERENCES appuser(userid) ON DELETE SET NULL,
  userenteredchat BOOLEAN NOT NULL DEFAULT FALSE,
  adminenteredchat BOOLEAN NOT NULL DEFAULT FALSE,
  speakerid BIGINT REFERENCES appuser(userid) ON DELETE SET NULL,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (adminuserid, useruserid, deliveryid)
);

CREATE TABLE IF NOT EXISTS message (
  messageid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  messagedatetime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  msgcontent TEXT NOT NULL,
  roomid INTEGER NOT NULL REFERENCES chat(roomid) ON DELETE CASCADE,
  speakerid BIGINT REFERENCES appuser(userid) ON DELETE SET NULL,
  messagereaduser BOOLEAN NOT NULL DEFAULT FALSE,
  messagereadadmin BOOLEAN NOT NULL DEFAULT FALSE,
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_typeid ON product(typeid);
CREATE INDEX IF NOT EXISTS idx_product_categoryid ON product(categoryid);
CREATE INDEX IF NOT EXISTS idx_productdetail_productid ON productdetail(productid);
CREATE INDEX IF NOT EXISTS idx_productdetail_productstatus ON productdetail(productstatus);
CREATE INDEX IF NOT EXISTS idx_appuser_roleid ON appuser(roleid);
CREATE INDEX IF NOT EXISTS idx_address_userid ON address(userid);
CREATE INDEX IF NOT EXISTS idx_cart_userid ON cart(userid);
CREATE INDEX IF NOT EXISTS idx_order_userid ON productorder(userid);
CREATE INDEX IF NOT EXISTS idx_orderitem_orderid ON productorderitem(orderid);
CREATE INDEX IF NOT EXISTS idx_orderitem_deliveryid ON productorderitem(deliveryid);
CREATE INDEX IF NOT EXISTS idx_delivery_shipperid ON delivery(shipperid);
CREATE INDEX IF NOT EXISTS idx_chat_deliveryid ON chat(deliveryid);
CREATE INDEX IF NOT EXISTS idx_message_roomid ON message(roomid);

CREATE OR REPLACE VIEW product_details_view AS
WITH image_agg AS (
  SELECT
    pi.productid,
    ARRAY_AGG(i.url ORDER BY i.imageid) AS urls
  FROM productimage pi
  JOIN image i ON i.imageid = pi.imageid
  GROUP BY pi.productid
)
SELECT
  p.productid,
  p.productname,
  p.unitprice,
  p.description,
  p.soldqty,
  p.rating,
  COALESCE(image_agg.urls, ARRAY[]::TEXT[]) AS urls,
  p.typeid,
  t.typename AS type,
  c.categoryname AS category,
  p.categoryid,
  co.colourname AS colour,
  pd.colourid,
  co.hex,
  s.sizename AS size,
  pd.sizeid,
  pd.qty,
  pd.productstatus,
  pd.productdetailid,
  p.createdat,
  p.updatedat
FROM product p
JOIN productdetail pd ON pd.productid = p.productid
JOIN type t ON t.typeid = p.typeid
JOIN category c ON c.categoryid = p.categoryid
JOIN colour co ON co.colourid = pd.colourid
JOIN size s ON s.sizeid = pd.sizeid
LEFT JOIN image_agg ON image_agg.productid = p.productid;

CREATE OR REPLACE VIEW search_product AS
WITH detail_agg AS (
  SELECT
    pd.productid,
    ARRAY_AGG(co.colourname ORDER BY co.colourname, s.sizename) AS colour,
    ARRAY_AGG(co.hex ORDER BY co.colourname, s.sizename) AS hex,
    ARRAY_AGG(s.sizename ORDER BY co.colourname, s.sizename) AS size,
    COALESCE(SUM(pd.qty), 0) AS qty
  FROM productdetail pd
  JOIN colour co ON co.colourid = pd.colourid
  JOIN size s ON s.sizeid = pd.sizeid
  GROUP BY pd.productid
),
image_agg AS (
  SELECT
    pi.productid,
    COALESCE(ARRAY_AGG(DISTINCT i.url) FILTER (WHERE i.url IS NOT NULL), ARRAY[]::TEXT[]) AS urls
  FROM productimage pi
  JOIN image i ON i.imageid = pi.imageid
  GROUP BY pi.productid
)
SELECT
  p.productid,
  p.productname,
  p.description,
  p.unitprice,
  p.rating,
  p.soldqty,
  p.createdat,
  p.updatedat,
  t.typename AS type,
  c.categoryname AS category,
  COALESCE(detail_agg.colour, ARRAY[]::TEXT[]) AS colour,
  COALESCE(detail_agg.hex, ARRAY[]::TEXT[]) AS hex,
  COALESCE(detail_agg.size, ARRAY[]::TEXT[]) AS size,
  COALESCE(image_agg.urls, ARRAY[]::TEXT[]) AS urls,
  COALESCE(detail_agg.qty, 0) AS qty,
  CASE
    WHEN COALESCE(detail_agg.qty, 0) > 0 THEN 'in stock'
    ELSE 'out of stock'
  END AS productstatus
FROM product p
JOIN type t ON t.typeid = p.typeid
JOIN category c ON c.categoryid = p.categoryid
JOIN detail_agg ON detail_agg.productid = p.productid
LEFT JOIN image_agg ON image_agg.productid = p.productid;
